#Application Configuration
server:
  port: 0
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # DB -
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  # JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"