server:
  port: 8091

spring:
  # DB (Configuración para H2 en memoria en desarrollo)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  # ===============================
  # JPA / HIBERNATE (Configuración para desarrollo)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # Actuator
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    metrics:
      export:
        datadog:
          enabled: false
        prometheus:
          enabled: true