server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://shoppingdb-instance-1.cm1se64aqiv2.us-east-1.rds.amazonaws.com:5432/product_db
    username: estacoar87
    password: NGuxH|PfXe<tVlVR8PIw4)vU)52s
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: false

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    metrics:
      export:
        prometheus:
          enabled: true

logging:
  level:
    org.springframework.boot: DEBUG
