server:
  port: 0

spring:
  # DB
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  # Spring Boot Actuator
  management:
    endpoints:
      web:
        exposure:
          include: "health,info,metrics"
    metrics:
        prometheus:
          enabled: false
# Logging
logging:
  level:
    root: INFO
    academy.digitallab.store.product: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"