server:
  port: 8093
spring:
  datasource:
    url: jdbc:h2:mem:shoppingDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  # JPA / HIBERNATE (Configuración para desarrollo)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # Actuator (Exponer más endpoints en dev para depuración)
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    metrics:
      export:
        datadog:
          enabled: false
        prometheus:
          enabled: true